MyPasswordReset/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pwdresetapp.urls')),

    # 3. The link from email on which user clicks to reset password
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='pwdresetapp/password_reset_fill.html'),
         name='password_reset_confirm'),
    # 4. on successful reset of password
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='pwdresetapp/password_reset_complete.html'),
         name='password_reset_complete'),
   
]

pwdresetapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
app_name = 'myapp'
urlpatterns = [
    
    path('',views.index, name='index'),
    path('success/',views.success,name='success'),

     # urls for password reset
    #1. for entering email to reset password
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='pwdresetapp/password_reset.html',
    
    success_url=reverse_lazy('myapp:password_reset_done')),
         name='password_reset'),

    #2. for sending email to user who want to change password
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='pwdresetapp/password_reset_sent.html'),
         name='password_reset_done'),
    
    # # 3. The link from email on which user clicks to reset password
    # path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='pwdresetapp/password_reset_fill.html'),
    #      name='password_reset_confirm'),
    # # 4. on successful reset of password
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='pwdresetapp/password_reset_complete.html'),
    #      name='password_reset_complete'),
    

]

pwdresetapp/models.py
from django.db import models

# Create your models here.

pwdresetapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):

    return render(request, 'pwdresetapp/index.html')

def success(request):
    return HttpResponse("Password Reset Successfully")

pwdresetapp/templates/pwdresetapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Document</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>
<body>
    {% block body %} {% endblock body %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

pwdresetapp/templates/pwdresetapp/index.html
{% extends 'pwdresetapp/base.html' %}

{% block body %}
<h1>Hello There</h1>
<h2>Do you want to reset password?</h2><a href="{% url 'myapp:password_reset' %}">Click here!</a>
{% endblock %}

pwdresetapp/templates/pwdresetapp/password_reset.html
{% extends 'pwdresetapp/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container shadow bg-white jumbotron" style="margin-top:150px;margin-bottom:150px; width: 600px;height: 250px;border-radius: 20px;">
        <form method="post" >
        <h2 class="text-success text-center" style="padding-top: 20px;"> Do you want to reset your password? </h2>
        {% csrf_token %}
        <div class="text-center mt-4" style="align-content: center;">
          {{form|crispy}}
        </div>
        <div class="text-center">
        <input type="submit" value="Send Me Email" class="btn btn-success mt-4 mb-4">
    </div>
    </form>
</div>
{% endblock %}

pwdresetapp/templates/pwdresetapp/password_reset_complete.html
{% extends 'pwdresetapp/base.html' %}
{% block body %}
<div class="container shadow jumbotron bg-white" style="margin-top:200px;margin-bottom:150">
    <h2 class="text-success"> Congrats. The password has been changed!!! </h2>
    <h3>Do you want to login now?</h3>
    <a href="{% url 'myapp:success' %}" class="btn btn-primary">Login</a>
</div>
{% endblock %}

pwdresetapp/templates/pwdresetapp/password_reset_email.html
{% extends 'pwdresetapp/base.html' %}
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'club:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

{% endautoescape %}

pwdresetapp/templates/pwdresetapp/password_reset_fill.html
{% extends 'pwdresetapp/base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container shadow jumbotron bg-white" style="margin-top:200px;margin-bottom:150">
    <h2 style="text-align: center;"> Do you want to reset your password? </h2>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}<br>
        <input type="submit" value="Send" class="btn btn-primary">
    </form>
</div>
{% endblock %}

pwdresetapp/templates/pwdresetapp/password_reset_sent.html
{% extends 'pwdresetapp/base.html' %}
{% block body %}
<div class="container shadow jumbotron bg-white" style="margin-top:200px;margin-bottom:150px">
    <h2 class="text-success">Password reset sent!!! Check your email.</h2>
    <h3>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</h3>
</div>
{% endblock %}